/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbolishExpectDialog.java
 *
 * 
 */

package com.icss.happyfarm.ui;

import com.icss.happyfarm.bean.Decorate;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class AbolishExpectDialog extends javax.swing.JDialog {
    static Decorate decorate;     //商店中点击的装饰
    static BuyDecorateDialog parent;  //预览装饰对话框的父窗口
    static ShoppingDialog shParent;   //向预览装饰对话框中传商店窗口对象
    static MainFrame mParent;   //向预览装饰对话框中传主窗口对象
    static Icon housePath;
    /** Creates new form AbolishExpectDialog */
    public AbolishExpectDialog(BuyDecorateDialog parent, boolean modal,ShoppingDialog shParent,MainFrame mParent,Icon housePath,Decorate decorate) {
        super(parent, modal);
        AbolishExpectDialog.decorate = decorate;
        AbolishExpectDialog.parent = parent;
        AbolishExpectDialog.shParent = shParent;
        AbolishExpectDialog.mParent = mParent;
        AbolishExpectDialog.housePath = housePath;
        this.setLocation((parent.getWidth()-this.getWidth())/2+350, (parent.getHeight()-this.getHeight())/2+338);
        this.setTitle("取消预览");
        
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
				giveUp();
			}
        });
        this.setResizable(false);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblGiveUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblGiveUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/decoratePicture/取消预览.png"))); // NOI18N
        lblGiveUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGiveUpMouseClicked(evt);
            }
        });
        lblGiveUp.setBounds(60, 50, 102, 30);
        jLayeredPane1.add(lblGiveUp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void lblGiveUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiveUpMouseClicked
        giveUp();
}//GEN-LAST:event_lblGiveUpMouseClicked

    public void giveUp() {
         if(decorate.getDecorateType()==0) {
             JLabel house = (JLabel)mParent.getLblMain();    //获取主界面背景标签
             house.setIcon(housePath);
        } else if(decorate.getDecorateType()==1) {
             JLabel house = (JLabel)mParent.getLblHouseDecorate();    //获取主界面房子标签
             house.setIcon(housePath);
        } else if(decorate.getDecorateType()==2) {
             JLabel house = (JLabel)mParent.getLblDogHouse();    //获取主界面房子标签
             house.setIcon(housePath);
        } else {
            JLabel column = (JLabel)mParent.getLblColumn();    //获取主界面栅栏标签
            column.setIcon(housePath);
        }

        this.dispose();
        parent.dispose();
        shParent.setVisible(true);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AbolishExpectDialog dialog = new AbolishExpectDialog(parent, true,shParent,mParent,housePath,decorate);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblGiveUp;
    // End of variables declaration//GEN-END:variables

}
