/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuyResultDialog.java
 *
 * 
 */

package com.icss.happyfarm.ui;

import javax.swing.JDialog;

/**
 *
 * @author Administrator
 */
public class BuyResultDialog extends javax.swing.JDialog {
    static JDialog parent;
    static boolean result;
    /** Creates new form BuyResultDialog */
    public BuyResultDialog(JDialog parent, boolean modal,boolean result) {
        super(parent, modal);
        BuyResultDialog.result = result;
        this.setLocation((parent.getWidth()-this.getWidth())/2+285, (parent.getHeight()-this.getHeight())/2+305);
        this.setTitle("提示");
        initComponents();
        if(result) {
            if (parent instanceof BuySeedDialog) {
                lblText.setText("购买种子成功！");
            } else if (parent instanceof BuyToolDialog) {
                lblText.setText("购买道具成功！");
            } else {
                lblText.setText("购买装饰成功！");
            }
            lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/decoratePicture/购买成功.png")));
        } else {
            lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/decoratePicture/购买失败.png")));
        }
        this.setResizable(false);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblText = new javax.swing.JLabel();
        lblSure = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblText.setFont(new java.awt.Font("华文楷体", 1, 15)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 0, 0));
        lblText.setBounds(110, 90, 120, 40);
        jLayeredPane1.add(lblText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮.png"))); // NOI18N
        lblSure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSureMouseClicked(evt);
            }
        });
        lblSure.setBounds(130, 140, 66, 30);
        jLayeredPane1.add(lblSure, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/decoratePicture/购买成功.png"))); // NOI18N
        lblBack.setBounds(0, 0, 320, 180);
        jLayeredPane1.add(lblBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSureMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblSureMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuyResultDialog dialog = new BuyResultDialog(parent, true,result);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblSure;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables

}
