/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuySeedDialog.java
 *
 * 
 */

package com.icss.happyfarm.ui;

import com.icss.happyfarm.bean.Seed;
import com.icss.happyfarm.stype.User;
import com.icss.happyfarm.util.DbUtil;
import com.icss.happyfarm.util.ShoppingBag;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
 * @author Administrator
 */
public class BuySeedDialog extends javax.swing.JDialog {
    static ShoppingDialog parent;
    static private Seed seed;
    static private MainFrame mf;
    int usedMoney;        //购买花费
    ShoppingBag bag;
    boolean canBuy = true;    //用户能否购买
    User user;
    int userMoney;    //用户所剩金币
    DbUtil util=new DbUtil();
    Document doc = null;
    /** Creates new form BuySeedDialog */
    public BuySeedDialog(ShoppingDialog parent, boolean modal,Seed seed,MainFrame mf) {
        super(parent, modal);
        BuySeedDialog.seed = seed;
        BuySeedDialog.mf = mf;
        user = MainFrame.getUser();
        this.setLocation((parent.getWidth()-this.getWidth())/2+198, (parent.getHeight()-this.getHeight())/2+194);
        this.setTitle("购买种子");        
        initComponents();
        setContent();

        doc=lblMiddle.getDocument();
        doc.addDocumentListener(new DocumentListener(){

            public void insertUpdate(DocumentEvent e) {
                changeMoney();
            }

            public void removeUpdate(DocumentEvent e) {
                changeMoney();
            }

            public void changedUpdate(DocumentEvent e) {
                changeMoney();
            }

        });
        this.setResizable(false);
        this.setVisible(true);
        
    }

     public void changeMoney() {

        try {
            int a = 0;
            String str = lblMiddle.getText().trim();
            char c = str.charAt(0);
            if(c=='-') {
                a = 1;
            } else if (!str.equals("")) {
                a = Integer.parseInt(str);
                if (a == 0) {
                    a = 1;
                } else if (a > 99) {
                    a = 99; 
                }
            }
             lblSeedTotalPrice.setText("" + seed.getSeedPrice() * a);
             check();
             lblMiddle.setText("     " + a);
        } catch (Exception e) {
        }
    }
    public void setContent() {
        lblSeedPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/seedPicture/"+seed.getSeedName()+".png")));
        lblExperience.setText(""+seed.getExperience());
        lblLevel.setText(""+seed.getLevel());
        lblSeedExpect.setText(""+seed.getExpectQuantity());
        lblFruitPrice.setText(""+seed.getFruitPrice());
        lblFruitTotalPrice.setText(""+seed.getFruitPrice()*seed.getExpectQuantity());
        lblSeedName.setText(seed.getSeedName());
        lblMiddle.setText("     "+1);
        lblSeedTotalPrice.setText(""+seed.getSeedPrice());
        lblSeedTime.setText(""+seed.getHarvestTime());
        lblSeedType.setText(seed.getCropSeason()+"季作物");
        lblMessage.setText(seed.getExplain());
        lblMessage.setFont(new java.awt.Font("宋体", 0, 11)); // NOI18N
        //lblMessage.setForeground(new java.awt.Color(0, 0, 255));

        //检测能否购买
        check();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblSeedPicture = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        lblSeedTotalPrice = new javax.swing.JLabel();
        lblSeedName = new javax.swing.JLabel();
        lblSeedType = new javax.swing.JLabel();
        lblSeedTime = new javax.swing.JLabel();
        lblSeedExpect = new javax.swing.JLabel();
        lblFruitTotalPrice = new javax.swing.JLabel();
        lblExperience = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblSure = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblMiddle = new javax.swing.JTextField();
        lblLift = new javax.swing.JLabel();
        lblFruitPrice = new javax.swing.JLabel();
        lblNotice = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblBuySeed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSeedPicture.setBounds(20, 10, 130, 130);
        jLayeredPane1.add(lblSeedPicture, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblm.setFont(new java.awt.Font("宋体", 1, 12));
        lblm.setForeground(new java.awt.Color(255, 102, 0));
        lblm.setText("金币：");
        lblm.setBounds(42, 140, 40, 30);
        jLayeredPane1.add(lblm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSeedTotalPrice.setForeground(new java.awt.Color(204, 102, 0));
        lblSeedTotalPrice.setBounds(80, 140, 50, 30);
        jLayeredPane1.add(lblSeedTotalPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSeedName.setFont(new java.awt.Font("宋体", 0, 24));
        lblSeedName.setForeground(new java.awt.Color(0, 204, 153));
        lblSeedName.setBounds(250, 10, 90, 40);
        jLayeredPane1.add(lblSeedName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSeedType.setFont(new java.awt.Font("新宋体", 0, 12));
        lblSeedType.setBounds(250, 55, 70, 20);
        jLayeredPane1.add(lblSeedType, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSeedTime.setFont(new java.awt.Font("新宋体", 0, 12)); // NOI18N
        lblSeedTime.setBounds(250, 80, 30, 20);
        jLayeredPane1.add(lblSeedTime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSeedExpect.setFont(new java.awt.Font("新宋体", 0, 12));
        lblSeedExpect.setBounds(250, 105, 30, 20);
        jLayeredPane1.add(lblSeedExpect, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFruitTotalPrice.setFont(new java.awt.Font("新宋体", 0, 12));
        lblFruitTotalPrice.setBounds(280, 150, 40, 20);
        jLayeredPane1.add(lblFruitTotalPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblExperience.setFont(new java.awt.Font("新宋体", 0, 12));
        lblExperience.setBounds(250, 175, 20, 20);
        jLayeredPane1.add(lblExperience, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblLevel.setFont(new java.awt.Font("新宋体", 0, 12));
        lblLevel.setBounds(250, 200, 20, 20);
        jLayeredPane1.add(lblLevel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮.png"))); // NOI18N
        lblSure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSureMouseClicked(evt);
            }
        });
        lblSure.setBounds(120, 300, 70, 30);
        jLayeredPane1.add(lblSure, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/取消按钮.png"))); // NOI18N
        lblNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoMouseClicked(evt);
            }
        });
        lblNo.setBounds(210, 300, 70, 30);
        jLayeredPane1.add(lblNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/right.png"))); // NOI18N
        lblRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRightMouseClicked(evt);
            }
        });
        lblRight.setBounds(107, 172, 20, 30);
        jLayeredPane1.add(lblRight, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMiddle.setText("jTextField1");
        lblMiddle.setBounds(51, 175, 50, 25);
        jLayeredPane1.add(lblMiddle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblLift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/lift.png"))); // NOI18N
        lblLift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLiftMouseClicked(evt);
            }
        });
        lblLift.setBounds(32, 175, 20, 20);
        jLayeredPane1.add(lblLift, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFruitPrice.setFont(new java.awt.Font("新宋体", 0, 12));
        lblFruitPrice.setBounds(280, 130, 30, 20);
        jLayeredPane1.add(lblFruitPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lblNotice.setBounds(120, 275, 160, 20);
        jLayeredPane1.add(lblNotice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMessage.setFont(new java.awt.Font("新宋体", 0, 12));
        lblMessage.setBounds(20, 240, 360, 40);
        jLayeredPane1.add(lblMessage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBuySeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/seedPicture/购买种子.png"))); // NOI18N
        lblBuySeed.setBounds(0, 0, 400, 340);
        jLayeredPane1.add(lblBuySeed, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLiftMouseClicked
        //String str = ((JLabel)evt.getSource()).getName().trim();
        int i = Integer.parseInt(lblMiddle.getText().trim());
        if(i>1) {
            lblMiddle.setText("     "+ --i);
        } else {
            lblMiddle.setText("     "+ 1);
        }
        lblSeedTotalPrice.setText(""+seed.getSeedPrice()*i);
        //检测能否购买
        check();
    }//GEN-LAST:event_lblLiftMouseClicked

    private void lblRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRightMouseClicked
        int i = Integer.parseInt(lblMiddle.getText().trim());
        if(i<99) {
            lblMiddle.setText("     "+ ++i);
        } else {
            lblMiddle.setText("     "+ 99);
        }
        lblSeedTotalPrice.setText(""+seed.getSeedPrice()*i);
        //检测能否购买
        check();
    }//GEN-LAST:event_lblRightMouseClicked

    private void lblNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblNoMouseClicked
    //检测是否可以购买
    public void check() {
        userMoney = getUserMoneyNow();
        if(userMoney<0 || user.getUserLevel()<seed.getLevel()) {
            if(userMoney<0) {
                 lblNotice.setText("对不起，你的金币不足！");
             }else if( user.getUserLevel()<seed.getLevel()) {
                 lblNotice.setText("对不起，你的等级不足！");
             } else {
                 lblNotice.setText("对不起，你的金币与等级均不足！");
             }
             canBuy = false;   //不能购买
             lblSure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮1.png")));
        } else {
            lblNotice.setText("");
            canBuy = true;   //能购买
            lblSure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮.png")));
        }
    }
    //用户购买后有多少钱
    public int getUserMoneyNow() {
         //购买花费
        usedMoney = Integer.parseInt(lblSeedTotalPrice.getText().toString());
        userMoney = Integer.parseInt(mf.getLblMoney().getText())-usedMoney;
        return userMoney;
    }
    private void lblSureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSureMouseClicked

        String sql2 = null;
        //购买数量
        int quantity = Integer.parseInt(lblMiddle.getText().trim());  //!!!!!!!
        //购买后有多少钱
        userMoney = getUserMoneyNow();
        if(!canBuy) {
             return ;
        } else {           
            bag = new ShoppingBag(user);   //实例化购物袋
            seed.setSeedQuantity(quantity);   //向种子中添加购买数量
            boolean have = bag.addSeedsToShoppingBag(seed.getSeedId()+"", seed);   //将要购买的种子添加到购物袋中去
            if(have) {   //如果该种子已经购买了，则数量相加
                Seed  sd  = (Seed)(bag.getItems().get(seed.getSeedId()+""));
                int seedQuantity = sd.getSeedQuantity();
                sql2 = "update t_goods set seedQuantity="+seedQuantity+" where cropId='"
                        +seed.getSeedId()+"' and userId="+user.getUserId();
            } else {   //将种子添加到商品表中
                sql2 = "insert into t_goods (cropId,seedQuantity,userId) " +
                        "values ('"+seed.getSeedId()+"',"+quantity+","+user.getUserId()+")";
            }
            util.execute(sql2);
             //页面显示修改
            mf.getLblMoney().setText(""+userMoney);
             //数据库中修改用户的金币数
            String sql1 = "update userl set userMoney="+userMoney+" where userId="+user.getUserId()+"";
            util.execute(sql1);
            util.close();
            //根据是否购买成功生成对话框
            BuyResultDialog bdr = new BuyResultDialog(BuySeedDialog.this,true,true);
            this.dispose();
        }
       
        
    }//GEN-LAST:event_lblSureMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuySeedDialog dialog = new BuySeedDialog(parent, true,seed,mf);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBuySeed;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblFruitPrice;
    private javax.swing.JLabel lblFruitTotalPrice;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLift;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField lblMiddle;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNotice;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblSeedExpect;
    private javax.swing.JLabel lblSeedName;
    private javax.swing.JLabel lblSeedPicture;
    private javax.swing.JLabel lblSeedTime;
    private javax.swing.JLabel lblSeedTotalPrice;
    private javax.swing.JLabel lblSeedType;
    private javax.swing.JLabel lblSure;
    private javax.swing.JLabel lblm;
    // End of variables declaration//GEN-END:variables

    

}
