/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuyToolDialog.java
 *
 * 
 */
package com.icss.happyfarm.ui;

import com.icss.happyfarm.bean.Tools;
import com.icss.happyfarm.stype.User;
import com.icss.happyfarm.util.DbUtil;
import com.icss.happyfarm.util.ShoppingBag;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
 * @author Administrator
 */
public class BuyToolDialog extends javax.swing.JDialog {

    static ShoppingDialog parent;
    private static Tools tool;
    static private MainFrame mf;
    User user;
    int userMoney;   //用户购买后有多少钱
    int price;   //购买花费
    boolean canBuy = true;  //能否购买
    ShoppingBag bag;
    DbUtil util=new DbUtil();
    int i = 0;
    Document doc=null;
    /** Creates new form BuyToolDialog */
    public BuyToolDialog(ShoppingDialog parent, boolean modal, Tools tool, MainFrame mf) {
        super(parent, modal);
        BuyToolDialog.tool = tool;
        BuyToolDialog.mf = mf;
        user = MainFrame.getUser();
        this.setLocation((parent.getWidth() - this.getWidth()) / 2 + 198, (parent.getHeight() - this.getHeight()) / 2 + 220);
        this.setTitle("购买道具");
        initComponents();
        setContent();

        doc=lblMiddleText.getDocument();
        doc.addDocumentListener(new DocumentListener(){

            public void insertUpdate(DocumentEvent e) {
                changeMoney();
            }

            public void removeUpdate(DocumentEvent e) {
                changeMoney();
            }

            public void changedUpdate(DocumentEvent e) {
                changeMoney();
            }

        });
        this.setResizable(false);
        this.setVisible(true);

        
    }

    public void changeMoney() {
        try {
            String str = lblMiddleText.getText().trim();
            char c = str.charAt(0);
            if(c=='-') {
                i = 1;
            } else if (!str.equals("")) {
                i = Integer.parseInt(str);
                if (i == 0) {
                    i = 1;
                } else if(i>99){
                    i = 99;
                }
            }
             lblPrice.setText("" + tool.getToolsPrice() * i);
             check();
             lblMiddleText.setText("     " + i);
        } catch (Exception e) {
        }
    }
    public void setContent() {
        this.lblToolPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/toolsPicture/" + tool.getToolsName() + ".png")));
        this.lblName.setText(tool.getToolsName());
        if (tool.getToolsType() == 0) {
            this.lblType.setText("  化肥");
            lblMiddleText.setText("     "+1);
        } else {
            this.lblLeft.setVisible(false);
            this.lblMiddleText.setVisible(false);
            this.lblRight.setVisible(false);
            this.lblBuyQuantity.setVisible(false);
            if(tool.getToolsType() == 1) {
                this.lblType.setText(" 狗");
            } else {
                this.lblType.setText(" 狗粮");
            }
            
        }
        this.lblText.setText(tool.getExplain());

        this.lblPrice.setText("" + tool.getToolsPrice());

        //检测能否购买
        check();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblToolPicture = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        lblMiddleText = new javax.swing.JTextField();
        lblRight = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBuyQuantity = new javax.swing.JLabel();
        lblNotice = new javax.swing.JLabel();
        lblSure = new javax.swing.JLabel();
        lblGiveup = new javax.swing.JLabel();
        lblBuyToolBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblToolPicture.setBounds(20, 20, 130, 130);
        jLayeredPane1.add(lblToolPicture, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/lift.png"))); // NOI18N
        lblLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeftMouseClicked(evt);
            }
        });
        lblLeft.setBounds(30, 155, 20, 30);
        jLayeredPane1.add(lblLeft, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMiddleText.setText("   1");
        lblMiddleText.setBounds(52, 160, 50, 25);
        jLayeredPane1.add(lblMiddleText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/right.png"))); // NOI18N
        lblRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRightMouseClicked(evt);
            }
        });
        lblRight.setBounds(110, 156, 20, 30);
        jLayeredPane1.add(lblRight, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblPrice.setFont(new java.awt.Font("新宋体", 0, 14));
        lblPrice.setBounds(200, 55, 60, 20);
        jLayeredPane1.add(lblPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblText.setFont(new java.awt.Font("新宋体", 0, 12));
        lblText.setBounds(150, 150, 230, 60);
        jLayeredPane1.add(lblText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblType.setFont(new java.awt.Font("新宋体", 1, 12));
        lblType.setForeground(new java.awt.Color(0, 51, 204));
        lblType.setBounds(200, 80, 50, 20);
        jLayeredPane1.add(lblType, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblName.setFont(new java.awt.Font("宋体", 0, 24));
        lblName.setForeground(new java.awt.Color(0, 204, 102));
        lblName.setBounds(200, 10, 170, 40);
        jLayeredPane1.add(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBuyQuantity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/toolsPicture/buyQuantity.png"))); // NOI18N
        lblBuyQuantity.setBounds(20, 180, 130, 40);
        jLayeredPane1.add(lblBuyQuantity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lblNotice.setBounds(130, 210, 140, 20);
        jLayeredPane1.add(lblNotice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮.png"))); // NOI18N
        lblSure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSureMouseClicked(evt);
            }
        });
        lblSure.setBounds(120, 230, 80, 30);
        jLayeredPane1.add(lblSure, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblGiveup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/取消按钮.png"))); // NOI18N
        lblGiveup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGiveupMouseClicked(evt);
            }
        });
        lblGiveup.setBounds(210, 230, 70, 30);
        jLayeredPane1.add(lblGiveup, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBuyToolBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/toolsPicture/购买道具背景2.png"))); // NOI18N
        lblBuyToolBack.setText("jLabel1");
        lblBuyToolBack.setBounds(0, 0, 400, 270);
        jLayeredPane1.add(lblBuyToolBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGiveupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiveupMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblGiveupMouseClicked

    private void lblLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeftMouseClicked
        int i = Integer.parseInt(lblMiddleText.getText().trim());
        if (i > 1) {
            lblMiddleText.setText("     " + --i);
        } else {
            lblMiddleText.setText("     " + 1);
        }
        lblPrice.setText("" + tool.getToolsPrice() * i);
        //检测能否购买
        check();
    }//GEN-LAST:event_lblLeftMouseClicked

    private void lblRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRightMouseClicked
        int i = Integer.parseInt(lblMiddleText.getText().trim());
        if (i < 99) {
            lblMiddleText.setText("     " + ++i);
        } else {
            lblMiddleText.setText("     " + 99);
        }
        lblPrice.setText("" + tool.getToolsPrice() * i);
        //检测能否购买
        check();
    }//GEN-LAST:event_lblRightMouseClicked

    public void check() {
        //获得购买结余
        userMoney = getUserMoneyNow();
        if (userMoney < 0) {
            lblNotice.setText("对不起，你的金币不足！");
            canBuy = false;   //不能购买
            lblSure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮1.png")));
        } else {
            lblNotice.setText("");
            canBuy = true;   //能购买
            lblSure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮.png")));
        }
    }
    public int getUserMoneyNow() {
        //购买花费
        int pirce = Integer.parseInt(lblPrice.getText().trim().toString());
        //购买结余
        int uMoney = Integer.parseInt(mf.getLblMoney().getText());
        return (uMoney - pirce);
    }
    private void lblSureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSureMouseClicked

        if (canBuy) {            
            //获得购买结余
            userMoney = getUserMoneyNow();
            bag = new ShoppingBag(user);   //实例化购物袋
            //购买数量
            int quantity = Integer.parseInt(lblMiddleText.getText().trim().toString());
            tool.setBuyQuantity(quantity);   //向化肥中添加购买数量
            boolean have = bag.addToolToShoppingBag(tool.getToolsId(), tool);   //将要购买的道具添加到购物袋中去
            String sql2 = null;
            if (tool.getToolsType() == 0) {
                if (have) {   //如果该化肥已经购买了，则数量相加
                    Tools tl = (Tools) (bag.getItems().get(tool.getToolsId()));
                    int buyQuantity = tl.getBuyQuantity();
                    sql2 = "update t_goods set toolsQuantity=" + buyQuantity + "" +
                            " where toolsId='" + tool.getToolsId() + "' and userId="+user.getUserId();
                } else {   //修改此类种子的购买属性和购买数量
                    sql2 = "insert into t_goods (toolsId,toolsQuantity,userId) " +
                        "values ('"+tool.getToolsId()+"',"+quantity+","+user.getUserId()+")";
                }
            } else {
                if (!have) {
                    //如果购物袋中还没有购买该道具，则更改道具是否被购买属性
                    sql2 = "insert into t_goods (toolsId,toolsQuantity,userId) " +
                        "values ('"+tool.getToolsId()+"',"+quantity+","+user.getUserId()+")";
                } else {
                    //如果有装饰，购买失败
                     sql2 = "update t_goods set toolsQuantity=1 where " +
                             "toolsId='" + tool.getToolsId() + "' and userId="+user.getUserId();
                    BuyResultDialog bdr = new BuyResultDialog(BuyToolDialog.this, true, false);
                    return ;
                }
            }
            util.execute(sql2);
            //页面显示修改
            mf.getLblMoney().setText("" + userMoney);
            //数据库中修改用户的金币数
            String sql1 = "update userl set userMoney=" + userMoney + " where userId=" + user.getUserId() + "";
            util.execute(sql1);
            util.close();
            //根据是否购买成功生成对话框
            BuyResultDialog bdr = new BuyResultDialog(BuyToolDialog.this, true, true);
            this.dispose();
        }

}//GEN-LAST:event_lblSureMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                BuyToolDialog dialog = new BuyToolDialog(parent, true, tool, mf);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBuyQuantity;
    private javax.swing.JLabel lblBuyToolBack;
    private javax.swing.JLabel lblGiveup;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JTextField lblMiddleText;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNotice;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblSure;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblToolPicture;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
