/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SaleFruitDialog.java
 *
 * 
 */
package com.icss.happyfarm.ui;

import com.icss.happyfarm.bean.Fruit;
import com.icss.happyfarm.stype.User;
import com.icss.happyfarm.util.DbUtil;

/**
 *
 * @author Administrator
 */
public class SaleFruitDialog extends javax.swing.JDialog {

    static private Fruit fruit;
    static private WareHouseDialog parent;
    static MainFrame mf;    //主界面
    User user;
    DbUtil util = new DbUtil();
    //要卖出的果实数量
    int quantity;
    int i = 0;
    //JLabel price;  //仓库对话框中的果实总价值标签

    /** Creates new form SaleFruitDialog */
    public SaleFruitDialog(WareHouseDialog parent, boolean modal, Fruit fruit, MainFrame mf) {
        super(parent, modal);
        SaleFruitDialog.parent = parent;
        SaleFruitDialog.mf = mf;
        SaleFruitDialog.fruit = fruit;
        user = MainFrame.getUser();
        //price = parent.getLblResultText();
        this.setLocation((parent.getWidth() - this.getWidth()) / 2 + 208, (parent.getHeight() - this.getHeight()) / 2 + 240);
        this.setTitle("卖出果实");
        initComponents();
        setContent();
        this.setResizable(false);
        this.setVisible(true);
    }

    private void setContent() {
        //显示果实属性
        lblFruitPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/seedPicture/" + fruit.getFruitName() + ".png")));
        lblFruitName.setText(fruit.getFruitName());
        lblFruitPrice.setText("" + fruit.getFruitPrice());
        lblMax.setText("" + fruit.getQuantity());
        lblTotalPrice.setText("" + fruit.getFruitPrice() * fruit.getQuantity());
        lblMiddle.setText("  " + fruit.getQuantity());
        lblSuoText.setText(fruit.getLock());
        if (fruit.getLock().equals("未上锁")) {
            lblSuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/锁定.png")));
        } else {
            lblSuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/解锁.png")));
            lblTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/卖出按钮1.png")));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblFruitPicture = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblMiddle = new java.awt.TextField();
        lblLeft = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblTrue = new javax.swing.JLabel();
        lblFalse = new javax.swing.JLabel();
        lblFruitPrice = new javax.swing.JLabel();
        lblSuo = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblFruitName = new javax.swing.JLabel();
        lblSuoText = new javax.swing.JLabel();
        lblSaleFruitBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFruitPicture.setBounds(22, 39, 120, 120);
        jLayeredPane1.add(lblFruitPicture, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/right.png"))); // NOI18N
        lblRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRightMouseClicked(evt);
            }
        });
        lblRight.setBounds(120, 165, 20, 30);
        jLayeredPane1.add(lblRight, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMiddle.setText("textField1");
        lblMiddle.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                lblMiddleTextValueChanged(evt);
            }
        });
        lblMiddle.setBounds(60, 168, 55, 25);
        jLayeredPane1.add(lblMiddle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/lift.png"))); // NOI18N
        lblLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeftMouseClicked(evt);
            }
        });
        lblLeft.setBounds(40, 168, 20, 20);
        jLayeredPane1.add(lblLeft, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMax.setFont(new java.awt.Font("新宋体", 0, 12));
        lblMax.setBounds(128, 193, 20, 20);
        jLayeredPane1.add(lblMax, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/卖出按钮.png"))); // NOI18N
        lblTrue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrueMouseClicked(evt);
            }
        });
        lblTrue.setBounds(110, 235, 80, 30);
        jLayeredPane1.add(lblTrue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFalse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/cancel.png"))); // NOI18N
        lblFalse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFalseMouseClicked(evt);
            }
        });
        lblFalse.setBounds(200, 230, 70, 40);
        jLayeredPane1.add(lblFalse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lblFruitPrice.setBounds(280, 115, 30, 20);
        jLayeredPane1.add(lblFruitPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSuo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSuoMouseClicked(evt);
            }
        });
        lblSuo.setBounds(260, 185, 50, 30);
        jLayeredPane1.add(lblSuo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lblTotalPrice.setBounds(280, 143, 40, 20);
        jLayeredPane1.add(lblTotalPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFruitName.setFont(new java.awt.Font("宋体", 0, 24));
        lblFruitName.setForeground(new java.awt.Color(0, 204, 153));
        lblFruitName.setBounds(210, 30, 100, 40);
        jLayeredPane1.add(lblFruitName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSuoText.setFont(new java.awt.Font("宋体", 1, 14));
        lblSuoText.setForeground(new java.awt.Color(153, 153, 153));
        lblSuoText.setBounds(210, 185, 60, 30);
        jLayeredPane1.add(lblSuoText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblSaleFruitBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/卖出果实.png"))); // NOI18N
        lblSaleFruitBack.setText("jLabel1");
        lblSaleFruitBack.setBounds(0, 0, 380, 280);
        jLayeredPane1.add(lblSaleFruitBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRightMouseClicked
        i = Integer.parseInt(lblMiddle.getText().trim());
        if (i < fruit.getQuantity()) {
            lblMiddle.setText("  " + ++i);
        } else {
            lblMiddle.setText("  " + fruit.getQuantity());
        }
        lblTotalPrice.setText("" + fruit.getFruitPrice() * i);
    }//GEN-LAST:event_lblRightMouseClicked

    private void lblLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeftMouseClicked
        i = Integer.parseInt(lblMiddle.getText().trim());
        if (i > 1) {
            lblMiddle.setText("  " + --i);
        } else {
            lblMiddle.setText("  " + 1);
        }
        lblTotalPrice.setText("" + fruit.getFruitPrice() * i);
    }//GEN-LAST:event_lblLeftMouseClicked

    private void lblFalseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFalseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblFalseMouseClicked

    private void lblSuoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuoMouseClicked

        if (lblSuoText.getText().equals("未上锁")) {
            //改变数据库中果实的锁定属性
            String sql = "update t_warehouse set lock='已锁定' where cropId=" + fruit.getFruitId() + " and userId=" + user.getUserId();
            util.execute(sql);
            util.close();

            lblTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/卖出按钮1.png")));
            lblSuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/解锁.png")));
            lblSuoText.setText("已锁定");
        } else {
            //改变数据库中果实的锁定属性
            String sql = "update t_warehouse set lock='未上锁' where cropId=" + fruit.getFruitId() + " and userId=" + user.getUserId();
            util.execute(sql);
            util.close();

            lblSuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/锁定.png")));
            lblTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/卖出按钮.png")));
            lblSuoText.setText("未上锁");
        }
        parent.initWareHouse();   //从新加载仓库

    }//GEN-LAST:event_lblSuoMouseClicked

    private void lblTrueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrueMouseClicked
        if (lblSuoText.getText().equals("未上锁")) {
            //要卖出的果实数量
            quantity = Integer.parseInt(lblMiddle.getText().trim());
            int fruitQuantity = fruit.getQuantity();
            int leaveQuantity = fruitQuantity - quantity;
            //全部卖出
            if (quantity == fruitQuantity) {
                String sql1 = "delete from t_warehouse where cropId=" + fruit.getFruitId() + " and userId=" + user.getUserId();
                mf.getWh().getItems().remove(fruit.getFruitId());
                //System.out.println(mf.getWh().getItems().values());
                updateUser(sql1);   //修改信息方法
                fruit.setVisible(false);

            } else {
                //修改果实的数量
                String sql2 = "update t_warehouse set quantity=" + leaveQuantity + " where cropId=" + fruit.getFruitId() + " and userId=" + user.getUserId();
                Fruit fruit1 = mf.getWh().getItems().get(fruit.getFruitId());
                fruit1.setQuantity(leaveQuantity);
                mf.getWh().getItems().put(fruit.getFruitId(), fruit1);

                updateUser(sql2);   //修改信息方法
            }
            parent.initWareHouse();   //从新加载仓库
        } else {
            return;
        }
    }//GEN-LAST:event_lblTrueMouseClicked

    private void lblMiddleTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_lblMiddleTextValueChanged
        try {
            String str = lblMiddle.getText().trim();
            char c = str.charAt(0);
            if(c=='-') {
                i = 1;
                lblMiddle.setText("   " + i);
            } else if (!str.equals("")) {
                i = Integer.parseInt(str);
                if (i == 0) {
                    i = 1;
                    lblMiddle.setText("  " + i);
                } else if (i > fruit.getQuantity()) {
                    i = fruit.getQuantity();
                    lblMiddle.setText("  " + i);
                } 
            }
             lblTotalPrice.setText("" + fruit.getFruitPrice() * i);             
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblMiddleTextValueChanged

    public void updateUser(String str) {

        this.dispose();  //关闭本窗口

        //用户收入
        int money = Integer.parseInt(lblTotalPrice.getText().trim());
        SaleFruitResultDialog result = new SaleFruitResultDialog(parent, true, quantity, money, fruit.getFruitName());
        util.execute(str);

        mf.getLblMoney().setText("" + user.addMoney(money));   //设置主界面用户金币显示
        util.close();

        parent.initWareHouse();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SaleFruitDialog dialog = new SaleFruitDialog(parent, true, fruit, mf);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblFalse;
    private javax.swing.JLabel lblFruitName;
    private javax.swing.JLabel lblFruitPicture;
    private javax.swing.JLabel lblFruitPrice;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblMax;
    private java.awt.TextField lblMiddle;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblSaleFruitBack;
    private javax.swing.JLabel lblSuo;
    private javax.swing.JLabel lblSuoText;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTrue;
    // End of variables declaration//GEN-END:variables
}
