/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SureSaleFruitDialog.java
 *
 * 
 */

package com.icss.happyfarm.ui;

import com.icss.happyfarm.bean.Fruit;
import com.icss.happyfarm.stype.User;
import com.icss.happyfarm.util.DbUtil;
import com.icss.happyfarm.util.WareHouse;
import java.util.Iterator;

/**
 *
 * @author Administrator
 */
public class SureSaleFruitDialog extends javax.swing.JDialog {
   static WareHouseDialog parent;
   private static WareHouse house;
   static MainFrame mf;   //主界面
   User user;
   DbUtil util=new DbUtil();
    /** Creates new form SureSaleFruitDialog */
    public SureSaleFruitDialog(WareHouseDialog parent, boolean modal,WareHouse house,MainFrame mf) {
        super(parent, modal);
        SureSaleFruitDialog.parent = parent;
        SureSaleFruitDialog.house = house;
        SureSaleFruitDialog.mf = mf;
        user = MainFrame.getUser();
        this.setLocation((parent.getWidth()-this.getWidth())/2+240, (parent.getHeight()-this.getHeight())/2+270);
        this.setTitle("确定");
        initComponents();
        lblTotalPrice.setText(" "+house.getTotalPrice());
        if(house.getTotalPrice()==0) {
            lblTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮1.png")));
        }
        this.setResizable(false);
        this.setVisible(true);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblTotalPrice = new javax.swing.JLabel();
        lblTrue = new javax.swing.JLabel();
        lblFalse = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTotalPrice.setFont(new java.awt.Font("宋体", 1, 14));
        lblTotalPrice.setForeground(new java.awt.Color(255, 153, 0));
        lblTotalPrice.setBounds(130, 115, 60, 30);
        jLayeredPane1.add(lblTotalPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定按钮.png"))); // NOI18N
        lblTrue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrueMouseClicked(evt);
            }
        });
        lblTrue.setBounds(90, 170, 66, 30);
        jLayeredPane1.add(lblTrue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFalse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/取消按钮.png"))); // NOI18N
        lblFalse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFalseMouseClicked(evt);
            }
        });
        lblFalse.setBounds(170, 165, 70, 40);
        jLayeredPane1.add(lblFalse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/确定卖出.png"))); // NOI18N
        lblBack.setBounds(0, 0, 322, 214);
        jLayeredPane1.add(lblBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTrueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrueMouseClicked

        if(house.getTotalPrice()==0) {
            return ;
        }
        this.dispose();
        SaleAllFruitResultDialog result = new SaleAllFruitResultDialog(SureSaleFruitDialog.this,true,house.getTotalPrice());
        
        //修改库存
        String sql1 = "delete from t_warehouse where lock='未上锁'and userId="+user.getUserId();
        for(Iterator iter = house.getItems().values().iterator();iter.hasNext();) {
            Fruit fruit = (Fruit)iter.next();
            if(fruit.getLock().equals("未上锁")) {
                mf.getWh().getItems().remove(fruit.getFruitId());
            }
        }
        util.execute(sql1);
        //修改用户金币

        mf.getLblMoney().setText("" +user.addMoney(house.getTotalPrice()));   //设置主界面用户金币显示   
        util.close();

        parent.initWareHouse();
        
    }//GEN-LAST:event_lblTrueMouseClicked

    private void lblFalseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFalseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblFalseMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SureSaleFruitDialog dialog = new SureSaleFruitDialog(parent, true,house,mf);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblFalse;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTrue;
    // End of variables declaration//GEN-END:variables

}
