/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WareHouseDialog.java
 *
 * 
 */
package com.icss.happyfarm.ui;

import com.icss.happyfarm.bean.Fruit;
import com.icss.happyfarm.stype.User;
import com.icss.happyfarm.util.WareHouse;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import java.awt.*;

/**
 *
 * @author Administrator
 */
public class WareHouseDialog extends javax.swing.JDialog {

    private JLabel lblFruit1;
    Fruit fruit = null;
    private Map<Integer, Fruit> itemFruits;
    private List<JLabel> text = new ArrayList<JLabel>();  //果实数量信息标签
    SaleFruitDialog saleFruit;
    WareHouse house;   //仓库工具类
    static MainFrame parent;   //主界面
    static User user;
    JLabel lblFruitText;    //果实数量信息

    /** Creates new form WareHouseDialog */
    public JLabel getLblFruitText() {
        return lblFruitText;
    }

    public JLabel getLblResultText() {
        return lblResultText;
    }

    public WareHouseDialog(MainFrame parent, boolean modal, User user) {
        super(parent, modal);
        WareHouseDialog.parent = parent;
        WareHouseDialog.user = user;
        this.setLocation((parent.getWidth() - this.getWidth()) / 2 - 100, (parent.getHeight() - this.getHeight()) / 2);
        this.setTitle("仓库");
        initComponents();
        initWareHouse();

        Toolkit tk=Toolkit.getDefaultToolkit();
        Image hand_img=tk.createImage(getClass().getResource("/com/icss/happyfarm/imag/bg/mouse.png"));
        Cursor hand=tk.createCustomCursor(hand_img,new Point(0,0),"MY_CURSOR");
        setCursor(hand);

        this.setResizable(false);
        this.setVisible(true);

    }

    //初始化加载仓库
    public void initWareHouse() {
        if (itemFruits != null) {
            //清空果实标签里面的内容
            for (Iterator iter = itemFruits.entrySet().iterator(); iter.hasNext();) {
                Fruit item = (Fruit) ((Entry) iter.next()).getValue();
                jWareHouseLayeredPane.remove(item);
            }
            itemFruits.clear();
        }

        house = new WareHouse(user);
        itemFruits = house.getItems();
        lblResultText.setText("" + house.getTotalPrice());
        //清空文本内容
        for (Iterator iter = text.iterator(); iter.hasNext();) {
            JLabel lbl = (JLabel) iter.next();
            jWareHouseLayeredPane.remove(lbl);
        }

        showFruits();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jWareHouseLayeredPane = new javax.swing.JLayeredPane();
        panelWareHouse = new javax.swing.JPanel();
        lblSaleFruit = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblResultText = new javax.swing.JLabel();
        lblJinBi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fruitList = new javax.swing.JList();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSaleFruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/卖出果实.jpg"))); // NOI18N
        lblSaleFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaleFruitMouseClicked(evt);
            }
        });

        lblText.setFont(new java.awt.Font("宋体", 1, 14));
        lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/当前果实总价值.jpg"))); // NOI18N

        lblResultText.setFont(new java.awt.Font("宋体", 1, 14));
        lblResultText.setForeground(new java.awt.Color(255, 51, 51));

        lblJinBi.setFont(new java.awt.Font("宋体", 1, 14));
        lblJinBi.setForeground(new java.awt.Color(255, 0, 0));
        lblJinBi.setText("金币：");

        javax.swing.GroupLayout panelWareHouseLayout = new javax.swing.GroupLayout(panelWareHouse);
        panelWareHouse.setLayout(panelWareHouseLayout);
        panelWareHouseLayout.setHorizontalGroup(
            panelWareHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWareHouseLayout.createSequentialGroup()
                .addComponent(lblText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJinBi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(lblSaleFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelWareHouseLayout.setVerticalGroup(
            panelWareHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaleFruit, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(lblText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblJinBi, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(lblResultText, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        panelWareHouse.setBounds(0, 270, 500, 40);
        jWareHouseLayeredPane.add(panelWareHouse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fruitList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(fruitList);

        jScrollPane1.setBounds(0, 30, 490, 240);
        jWareHouseLayeredPane.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/仓库背景.PNG"))); // NOI18N
        lblBackground.setText("jLabel1");
        lblBackground.setBounds(0, 0, 500, 310);
        jWareHouseLayeredPane.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jWareHouseLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jWareHouseLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSaleFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaleFruitMouseClicked
        //int price = house.getTotalPrice();
        new SureSaleFruitDialog(WareHouseDialog.this, true, house, parent);
    }//GEN-LAST:event_lblSaleFruitMouseClicked

    public void showFruits() {
        DefaultListModel listModel1 = new DefaultListModel();
        int j = 0;  //用来记录果实的位置
        int z = 0;  //用来记录垂直位置
        int a = 0;  //用来记录金币的位置
        int f = 0;

        //遍历HashMap中的果实
        for (Iterator iter = itemFruits.entrySet().iterator(); iter.hasNext();) {
            int i = 1000;   //用来设置图片显示的级别
            Entry es = (Entry) iter.next();
            fruit = (Fruit) es.getValue();
            lblFruitText = new JLabel();    //果实数量信息
            fruit.setBounds(18 + (100 * j++), 30 + (90 * z), 100, 80);     //果实的显示位置
            
            lblFruitText.setBounds(35 + (100 * a++), 110 + (90 * z), 100, 10);  //库存数量的显示位置
            lblFruitText.setText("" + fruit.getQuantity());
            String suo = fruit.getLock();
            JLabel lblIsSuo = new JLabel();
            if (suo.equals("已锁定")) {
                lblIsSuo.setBounds(20 + (100 * (j-1)), 80 + (90 * z), 20, 20);   //果实锁标签的显示位置
                lblIsSuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/小锁.png")));
            }

            JLabel lblLevel = new JLabel();   //果实等级
            lblLevel.setBounds(55 + (100 * f++), 80 + (90 * z), 25, 20);  //果实等级的显示位置
            lblLevel.setText(fruit.getLevel()+"级");
            lblLevel.setFont(new java.awt.Font("新宋体", 0, 12));
            lblLevel.setForeground(new java.awt.Color(0, 204, 153));

            if (fruit.getX() > (this.getWidth() - 50)) {       //显示位置超过框架是，换行显示
                j = 0;
                a = 0;
                f = 0;
                fruit.setBounds(18 + (100 * j++), 30 + (90 * ++z), 100, 80);     //果实的显示位置                 
                lblFruitText.setBounds(35 + (100 * a++), 110 + (90 * z), 100, 10);  //库存数量的显示位置
                lblFruitText.setText("" + fruit.getQuantity());

                lblLevel.setBounds(55 + (100 * f++), 80 + (90 * z), 25, 20);  //果实等级的显示位置
                lblLevel.setText(fruit.getLevel()+"级");
                if (suo.equals("已锁定")) {
                    lblIsSuo.setBounds(20 + (100 *(j-1)), 80 + (90 * z), 20, 20);   //果实锁标签的显示位置
                    lblIsSuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/fruit/小锁.png")));
                }
            }

            text.add(lblLevel);
            lblFruitText.setForeground(new java.awt.Color(0, 51, 204));
            text.add(lblFruitText);    //将数量标签添加到List中
            text.add(lblIsSuo);    //将数量标签添加到List中
            //设置seed Label的显示图标
            fruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icss/happyfarm/images/seedPicture/" + fruit.getFruitPicture())));


            jWareHouseLayeredPane.add(fruit, new Integer(++i));     //将果实标签添加到分层面板中去
            jWareHouseLayeredPane.add(lblFruitText, new Integer(++i));   //将金币显示标签添加到分层面板中去
            jWareHouseLayeredPane.add(lblLevel, new Integer(++i));   //将金币显示标签添加到分层面板中去
            jWareHouseLayeredPane.add(lblIsSuo,new Integer(++i));    //果实锁标签添加到分层面板中去
            //设置提示信息
            if (suo.equals("已锁定")) {
                fruit.setToolTipText("该果实已上锁，不能卖出！");
            } else {
                fruit.setToolTipText(fruit.getFruitName());
            }

            fruit.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                //给种子图标添加事件相应
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    fruitClicked(evt);
                }
            });
        }
        fruitList.setModel(listModel1);   //添加到滚动窗口中去
    }

    private void fruitClicked(java.awt.event.MouseEvent evt) {
        //System.out.println("hello");
        saleFruit = new SaleFruitDialog(WareHouseDialog.this, true, (Fruit) evt.getSource(), parent);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                WareHouseDialog dialog = new WareHouseDialog(parent, true, user);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList fruitList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane jWareHouseLayeredPane;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblJinBi;
    private javax.swing.JLabel lblResultText;
    private javax.swing.JLabel lblSaleFruit;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel panelWareHouse;
    // End of variables declaration//GEN-END:variables
}
